services:
  vireo.api.web:
    image: ${DOCKER_REGISTRY-}vireoapiweb
    build:
      context: .
      dockerfile: src/Vireo.Api.Web/Dockerfile
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: vireo
      POSTGRES_PASSWORD: vireo_password
      POSTGRES_DB: vireo_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data: